// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        // Windows uses the same configuration format as Web/Android.
        // Copy the values from your 'web' or 'android' configuration below.
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtur8jGTvXSq6ZIz_pgJVB58i3chJi108',
    appId: '1:808623945614:android:45359acdc1353f0378d6df',
    messagingSenderId: '808623945614',
    projectId: 'music-player-b4ee4',
    authDomain: 'music-player-b4ee4.firebaseapp.com',
    storageBucket: 'music-player-b4ee4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtur8jGTvXSq6ZIz_pgJVB58i3chJi108',
    appId: '1:808623945614:android:45359acdc1353f0378d6df',
    messagingSenderId: '808623945614',
    projectId: 'music-player-b4ee4',
    storageBucket: 'music-player-b4ee4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtur8jGTvXSq6ZIz_pgJVB58i3chJi108',
    appId:
        '1:808623945614:android:45359acdc1353f0378d6df', // Note: Using Android App ID. For best results, create a Web App in Firebase Console and use that ID.
    messagingSenderId: '808623945614',
    projectId: 'music-player-b4ee4',
    authDomain: 'music-player-b4ee4.firebaseapp.com',
    storageBucket: 'music-player-b4ee4.firebasestorage.app',
  );
}
